# Generated by Django 3.1.4 on 2021-01-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('po_premierze', models.BooleanField(default=False)),
            ],
        ),
    ]
