# Generated by Django 3.1.4 on 2021-01-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210107_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.IntegerField()),
                ('rodzaj', models.IntegerField(choices=[(5, 'Komedia'), (3, 'Dramat'), (2, 'Sci-Fi'), (1, 'Horror'), (0, 'Nieznany')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='extra_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.extrainfo'),
        ),
    ]
