# Generated by Django 3.1.4 on 2021-01-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210107_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recenzja',
            old_name='gwizdki',
            new_name='gwiazdki',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Sci-Fi'), (1, 'Horror'), (3, 'Dramat'), (5, 'Komedia'), (0, 'Nieznany')], default=0),
        ),
    ]
