# Generated by Django 3.1.4 on 2021-01-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210107_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(3, 'Dramat'), (1, 'Horror'), (5, 'Komedia'), (2, 'Sci-Fi'), (0, 'Nieznany')], default=0),
        ),
    ]
