# Generated by Django 3.1.4 on 2021-01-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210107_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(1, 'Horror'), (3, 'Dramat'), (2, 'Sci-Fi'), (5, 'Komedia'), (0, 'Nieznany')], default=0),
        ),
    ]
